version: '3'
services:
    web:
        image: nginx:latest
        container_name: web_safies
        ports:
            - "8000:80"
            - "3000:443"
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/web"
        depends_on:
            - "php"
            - "mongodb"

    php:
        image: nanoninja/php-fpm
        container_name: php_safies
        volumes:
            - ./etc/php-fpm/php7.2.ini:/usr/local/etc/php/php.ini
            - ./web:/web 

    mongodb:
        image: mongo
        container_name: mongo_safies
        volumes:
            - ./data/db/mongo:/data/db
        ports:
            - "27017:27017"
        command: --storageEngine wiredTiger
